# Use root/examplerootpass as user/password credentials
version: '3.8'

services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'springpass'
      MYSQL_DATABASE: 'ies'
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/mysql:/var/lib/mysql
