# Use root/examplerootpass as user/password credentials
version: '3.8'

services:
  mysql_db:
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    container_name: eDuca_db	
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'eDuca'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'springpass'
    ports:
      - "3306:3306"
    
